### PR TITLE
rename SparkAPI to Engine

### PR DESCRIPTION
**Pull request by erizocosmico**
Rename SparkAPI to Engine, continuing what was done in #110 

Changes in all the snippets in the documentation and README still pending.

### CODE REVIEW

**Comment by erizocosmico** [comment]
Rebased against master and ready to be merged

**Comment by bzz** [comment]
Running it locally with instructions from #111

**Comment by bzz** [comment]
Scala API works like a charm, will try PySpark as well

**Comment by bzz** [comment]
@erizocosmico `make docker-build` fails for me while following https://github.com/mcarmonaa/spark-api/tree/fix/doc-project-name#build-and-run-docker-to-get-a-jupyter-server

``` ---> Running in cb108e3f9965
The directory '/home/jovyan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jovyan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///opt/python-engine
    Complete output from command python setup.py egg_info:
    running egg_info
    creating sourced_engine.egg-info
    writing sourced_engine.egg-info/PKG-INFO
    writing dependency_links to sourced_engine.egg-info/dependency_links.txt
    writing requirements to sourced_engine.egg-info/requires.txt
    writing top-level names to sourced_engine.egg-info/top_level.txt
    writing manifest file 'sourced_engine.egg-info/SOURCES.txt'
    /opt/conda/lib/python3.6/site-packages/setuptools/dist.py:350: UserWarning: The version specified ('local') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    error: package directory 'sourced/spark' does not exist

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /opt/python-engine/
The command '/bin/sh -c pip install -e /opt/python-engine/' returned a non-zero code: 1
make: *** [docker-build] Error 1
```

`error: package directory 'sourced/spark' does not exist` - is that something wrong on my dev env (do not have any global python packages installed) or could be related to package rename?

**Comment by bzz** [comment]
Just noticed that history has been re-writted and I was using b2a31b605857005ac3521c69a6cb0aa32ba2c172 instead of now latest 0967d11 :/ 

Will try again now.

**Comment by bzz** [comment]
Example notebook and `./spark-shell` work very well. 

Shall we merge it?

**Pull request merged**
