### PR TITLE
implicits: make SparkAPI the entrypoint instead of using an implicit

### PR DESCRIPTION
**Pull request by erizocosmico**
I think adding this function to the spark session simplifies a bit the experience of the user of the library.

Before

```scala
spark.sqlContext.setConf("tech.sourced.api.repositories.path", "/path/to/files")
```

Now

```scala
spark.setRepositoriesPath("/path/to/files")
```

We could even check if the path exists and contains siva files there and so on in the future.

### CODE REVIEW

**Comment by bzz** [comment]
Nice! 

And how about pushing it a step further and making Python and Scala experience of using SparkAPI looking more similar?

In Scala this could mean adding a single entrypoint object that could hide some useful imports/configurations/etc, something like what was proposed in https://github.com/src-d/spark-api/pull/43#issuecomment-330501672:

```scala
val api = SparkAPI(spark, "path/to/siva/files")

api.getRepositories()
```

What do you think?

**Comment by erizocosmico** [comment]
Sounds great!

**Comment by erizocosmico** [comment]
Done @bzz!

Now it looks like this:

```scala
import tech.sourced.api.SparkAPI

val reposDf = SparkAPI(spark, "/path/to/foo").getRepositories
```

**Comment by bzz** [comment]
Looks awesome to me!

**Comment by bzz** [comment]
As soon as #43 is merged, shall this be rebased and example in README updated to use this as well?

**Comment by erizocosmico** [comment]
Yup!

One hairy thing that I noticed is that you now have to make 2 imports:

```scala
import tech.sourced.api.SparkAPI
import tech.sourced.api.Implicits._
```

Perhaps we could do something like:

```scala
package api {
  // define spark api
  // define implicits
}
```
Then it would become

```
import tech.sourced.api._
```

**Comment by bzz** [comment]
Oh, yes, that's a great catch - would be rally nice to have single `import tech.sourced.api._`!

**Comment by erizocosmico** [comment]
Working on that, then

**Comment by erizocosmico** [comment]
Fixed!

Moved implicits to a package object and made some things package-private to not make the user import a bunch of useless internal stuff.

Anyway, if the user reeeeeally wants to specify it can be done like so:

```scala
import tech.sourced.api.{SparkAPI, ApiDataFrame}
```

**Comment by erizocosmico** [comment]
Added documentation for the user-facing API as well.

**Comment by bzz** [comment]
The docs looks awesome. 


>One downside of this approach is that Java-generated classes look like:

Yes, but as soon as Java API is not the focus and it works in Python - that should be fine.

Let's get it merge then?

**Comment by erizocosmico** [comment]
:+1:

:shipit:

**Pull request merged**
