### PR TITLE
udf: implement UDF to query UAST nodes using XPath

### PR DESCRIPTION
**Pull request by ajnavarro**
Signed-off-by: Miguel Molina <miguel@erizocosmi.co>

### CODE REVIEW

**Comment by erizocosmico** [comment]
Last test of udf has an extra / on the second queryUAST

**Comment by erizocosmico** [comment]
Edit: nvm, no it doesnt

**Comment by ajnavarro** [comment]
Actually blocked by: https://github.com/bblfsh/client-scala/issues/19 and https://github.com/bblfsh/client-scala/issues/18

Having a look to the scala client to see if i find something.

**Comment by ajnavarro** [comment]
I tried using just scala, with the same result:

```scala
it should "query using queryUAST method of dataframe with custom cols" in {
    val spark = ss

    val pythonFilesDf = SparkAPI(spark, "/home/antonio/root-repositories-2")
      .getRepositories.getReferences.getHEAD.getCommits.getFirstReferenceCommit.getFiles
      .classifyLanguages

    val getTokens = (nodes: Seq[Array[Byte]]) =>
      nodes.map(Node.parseFrom).map(_.token)

    val u = udf(getTokens)

    val tokens = pythonFilesDf.extractUASTs()
      .queryUAST("//*[@roleIdentifier]")
      .queryUAST("/*[not(@roleIncomplete)]", "result", "result2")

    tokens.printSchema()

    val out = tokens.select("result2").withColumn("tokens", u(tokens("result2"))).select("tokens")

    out.show()
  }
```

**Comment by juanjux** [comment]
@ajnavarro @erizocosmico PTAL at the referenced issues of the scala client, we need more information (files, queries, etc) to debug them properly.

**Pull request closed without merging**
